### ISSUE TITLE
Game crashes on android control menu

### ISSUE THREAD

**Issue by IdentityTheft-bruh** [jigsaw-4277821/FNF-PsychEngine-Android-Support#12]
### Describe your bug here.

Game Crashes upon trying to load the android controls menu

### Command Prompt/Terminal logs (if existing)

```bash
android/AndroidControls.hx (line 20)
android/AndroidControlsMenu.hx (line 37)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by jigsaw-4277821** [comment]
It's fixed now
