### ISSUE TITLE
Keep Crash With Error

### ISSUE THREAD

**Issue by mcagabe19** [jigsaw-4277821/FNF-PsychEngine-Android-Support#14]
### Describe your problem here.

log:Paths.hx (line 350)
TitleState.hx (line 349)
TitleState.hx (line 214)
flixel/util/FlxTimer.hx (line 195)
flixel/util/FlxTimer.hx (line 285)
flixel/FlxGame.hx (line 745)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
Null Object Reference

### Are you modding a build from source or with Lua?

Source (I Think)

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

I Added My Optimized Stuff

**Comment by jigsaw-4277821** [comment]
If you added that stuff, that's why

**Comment by jigsaw-4277821** [comment]
If you added that stuff, that's why
