### ISSUE TITLE
All the songs crashes (except the original game ones)

### ISSUE THREAD

**Issue by Plotsh** [jigsaw-4277821/FNF-PsychEngine-Android-Support#15]
### Describe your bug here.

When i try openning any song (not a song from the weeks 1 - 6) the game crashes after 3 seconds of the song (i tried removing all my lua scripts and nothing changed)

### Command Prompt/Terminal logs (if existing)

```bash
no
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i just tried openning a mods folder song on psych 0.5.2h

**Comment by jigsaw-4277821** [comment]
If the game doesn't send a log, your phone is bad
