### ISSUE TITLE
Extension Videoview Bug or Mistake Idk

### ISSUE THREAD

**Issue by mcagabe19** [jigsaw-4277821/FNF-PsychEngine-Android-Support#2]
### Describe your bug here.

[Bug Here (I Can't Add Video Bruh)](https://youtu.be/X1VXuyu93aQ) 
if video not exist wait a 2 min

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by jigsaw-4277821** [comment]
It's a ploblem from your phone/tablet

**Comment by mcagabe19** [comment]
okey
