### ISSUE TITLE
Game crashes When i put Scripts/Turn off WIFI

### ISSUE THREAD

**Issue by N3hu** [jigsaw-4277821/FNF-PsychEngine-Android-Support#26]
### Describe your bug here.

in 0.5.1 this bug doesn't happend, but after this version, all the others got this annoying bug than crash the game if the game got scripts
Also this a new bug, when the wifi is off or i dont have wifi the game don't open, that never happend before with any version
(First screenshot is the WIFI crash, it freeze in a black screen and crashes, the LUA crash depends of the LUA, mostly crashed when i want to play another song after playing one with a LUA file)
![Screenshot_20220508-014659](https://user-images.githubusercontent.com/102952438/167282448-2ecc35b8-871a-4c49-b938-039e6a265c94.png)
![Screenshot_20220508-014736](https://user-images.githubusercontent.com/102952438/167282452-768f581d-dccc-4ef1-ae41-4794e9ef914e.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

I only put optimized assets

**Comment by jigsaw-4277821** [comment]
Phone ploblem
