### ISSUE TITLE
Is it possible to load mod files from external?

### ISSUE THREAD

**Issue by LazyBoy1002** [jigsaw-4277821/FNF-PsychEngine-Android-Support#32]
### What is your question?

The game has been eating up my internal storage, was wondering if it's possible to have psych load from SD card, or if I'm doing something wrong. (Tried copying the files from the apk to sdcard/.PsychEngine but it throws an error when I try to launch.)

**Comment by jigsaw-4277821** [comment]
You can't use your SD card to run the game files just for now

**Comment by StefanBETA2008** [comment]
Correct
