### ISSUE TITLE
Hey, I need some help.

### ISSUE THREAD

**Issue by Joalor64GH** [jigsaw-4277821/FNF-PsychEngine-Android-Support#33]
### Describe your problem here.

You port things to android, right? Well, I need help doing that. I want to add android support to my custom version of Psych Engine, but I have no idea how to. Can you please lend a hand?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

**Comment by DabKnight** [comment]
https://github.com/jigsaw-4277821/FNF-Porting-Stuff-Psych-Engine
